### ISSUE TITLE
Test-setup som f.eks. kan køre på localhost

### ISSUE THREAD

**Issue by baffioso** [frederiksberg/prod-app1-deployment#32]
Lige nu afhænger setup'et at et domæne (frb-data.dk) når reverse proxy opsættes. Der kan evt. laves nginx konfiguration til test, som kan burges når der udvikles på setup'et lokalt.

**Comment by nixen97** [comment]
implented in 124d439bac9b84b0a5e92a22cd0cc85efd8cbd8c.
