### ISSUE TITLE
Manglende pakker på en frisk server

### ISSUE THREAD

**Issue by kjoller** [frederiksberg/prod-app1-deployment#41]
Det kan godt være fordi jeg tester på en AWS-VM, men jeg manglede  `docker` og `docker-compose`. Og efter installation af docker skal man bruge `sudo make`, hvis man ikke laver docker-gruppe medlemskab til sin bruger.

Jeg havde `git` som standard, men det ved jeg ikke om man generelt kan forvente. Jeg fik også at vide at jeg manglede `gcc`, men det kan have været et issue i en Dockerfile et sted.

Generelt anbefalet at teste på en frisk maskine, og derefter notere hvad man har installeret og hvordan. Det kan sagtens være at alt er på plads med det image i bruger på DO.

**Comment by baffioso** [comment]
@kjoller Der stå lidt om afhængigheder her: https://github.com/frederiksberg/prod-app1-deployment#requirements 

Tænker du det skal uddybes/flyttes om i starten af README filen?

**Comment by kjoller** [comment]
Pinligt nok er jeg ikke kommet så langt. Dog tror at mangt en nystarter vil lave samme fejl. Måske en reference til afhængighedsafsnittet kan gøre det?
