### ISSUE TITLE
Services nede

### ISSUE THREAD

**Issue by baffioso** [frederiksberg/prod-app1-deployment#54]
Har igen fået besked fra UptimeRobot om at services har været nede omkring 
2020-01-18 06:52:57 UTC+0.
Kan se Nikto har cronjob kørende 06:13 så kan vel ikke være den der stadig spøger der??

Ifølge [Chronograf](https://monitor.frb-data.dk/sources/1/dashboards/2?tempVars%5Bhost%5D=master-node&lower=now%28%29%20-%2012h&zoomedLower=2020-01-18T06%3A02%3A23.816Z&zoomedUpper=2020-01-18T07%3A14%3A56.793Z) ser det ud til at Nikto tage godt fat i RAM og CPU. 
![image](https://user-images.githubusercontent.com/7534153/72665990-fe150e00-3a0d-11ea-90eb-0a8d8cae8dbf.png)

**Comment by baffioso** [comment]
@nixen97 fik besked om nedetid fra UpTimeRobot i går aftes og ligner at Nikto ikke længere kører som container - har du pillet den ned?

**Fra Uptime**
```bash
The monitor API - Hent GeoJSON (http://api.frb-data.dk/v1/data/genbrugs_oeer) is currently DOWN (Connection Timeout).

Event timestamp: 2020-01-21 22:26:48 UTC+0
```
Kan ikke umiddelbart se nogen heftig aktivitet på Chronograf - Mystisk

**Comment by nixen97** [comment]
Ja, jeg pillede den ned i weekenden, da den lavede noget rod.

Nej, jeg forstår heller ikke helt, hvad der skete i går. Jeg sad også og
fuldte med på Chronograf.

Mit bedste bud er proxy-loggen. Det virkede som om at det var lidt
tilfældigt hvilke services, der gik ned.

**Comment by nixen97** [comment]
Det første issue, hvar Nikto, som er taget ned.

Det andet kan jeg ikke identificere. Jeg lukker indtil videre.
